### ISSUE TITLE
网线问题解决了吗

### ISSUE THREAD

**Issue by echokk11** [MonchiLin/asus-rog-b550i-5800x-6900xt#1]
RT
5800x
tuf game b550m plus wifi
rx560 4G
倒是已经成功进入系统

**Comment by MonchiLin** [comment]
你试试这个驱动，放在/EFI/OC/Kexts 目录下，然后重启

https://github.com/Mieze/LucyRTL8125Ethernet

**Comment by echokk11** [comment]
嗯 我昨天自己找了这个可以了 ，多谢
