### ISSUE TITLE
关于第一阶段安装到磁盘剩余12分钟时死机的疑问

### ISSUE THREAD

**Issue by dockylf** [MonchiLin/asus-rog-b550i-5800x-6900xt#3]
你好，我的配置和你一模一样，都是5800x+rogb550i+6900xt，我的内存是科赋的3200 8G*2，硬盘1是sn850，硬盘2是希捷的1T机械。
我自己配置的EFI没有你的Above 4g decoding必须关闭的问题，可以正常跑码进第一阶段。但是在安装到磁盘剩余12分钟时，必死机。把kext全部去掉只剩lilu，virtualSMC, AppleALC，WEG，也一样每次必死机。
你在过程中有遇到这个问题么？是如何解决的？

My hardwares are appoximately the same with yours, 5800x+rogb550i+6900xt, Memory klev 3200 8G*2, harddrives are SN850 1T and Seagate HDD 1T.
I made EFI according to dortinia.git.io, didn't encount the problem of Above 4g decoding. However I met the other fatal error during installing to harddrive. when the time remain 12mins, the moment which suppose to reboot, system got frozen, and mouse couldn't move as well. I tried to remove all the kexts except lilu, virtualSMC, AppleALC, WEG, but it didn't work.
Have you met this problem?How did you fix it?

**Comment by MonchiLin** [comment]
优先按照 https://dortania.github.io/OpenCore-Install-Guide/AMD/zen.html 构建试试? 
同事也建议贴出 log, 不然没办法分析问题

**Comment by dockylf** [comment]
> 优先按照 https://dortania.github.io/OpenCore-Install-Guide/AMD/zen.html 构建试试?
> 同事也建议贴出 log, 不然没办法分析问题

感谢回复。又重新构建了一次，发现之前把cfgclock的那三个不适用amd的选项给勾上了（之前过不了跑代码的时候病急乱投医勾上的，后来忘了取消了）。取消那个三个选项后，就正常了。

**Comment by dockylf** [comment]
> 优先按照 https://dortania.github.io/OpenCore-Install-Guide/AMD/zen.html 构建试试?
> 同事也建议贴出 log, 不然没办法分析问题

感谢回复。又重新构建了一次，发现之前把cfgclock的那三个不适用amd的选项给勾上了（之前过不了跑代码的时候病急乱投医勾上的，后来忘了取消了）。取消那个三个选项后，就正常了。
